window.PREPARATOR_RULES = [
  {
    id: 'abaixo-acima',
    grupo: 'Vocabulário',
    severidade: 'revisar',
    titulo: 'Evitar abaixo/acima',
    descricao: 'O guia recomenda substituir abaixo/acima por a seguir, anterior ou anteriormente, conforme o contexto.',
    regex: '\\b(?:abaixo|acima)\\b',
    flags: 'gi',
  },
  {
    id: 'etc-com-e',
    grupo: 'Pontuação',
    severidade: 'segura',
    titulo: 'Etc. antecedido por e',
    descricao: 'Usar etc. sempre precedido de vírgula e nunca antecedido de e.',
    regex: '\\be\\s+etc\\.',
    flags: 'gi',
  },
  {
    id: 'quatorze',
    grupo: 'Grafia',
    severidade: 'segura',
    titulo: 'Preferir catorze',
    descricao: 'Em palavras que admitem c/qu, o guia recomenda a forma com c.',
    regex: '\\bquatorze\\b',
    flags: 'gi',
  },
  {
    id: 'quotidiano-quota',
    grupo: 'Grafia',
    severidade: 'segura',
    titulo: 'Preferir cotidiano/cota',
    descricao: 'O guia recomenda cotidiano e cota, não quotidiano e quota.',
    regex: '\\b(?:quotidiano|quota)\\b',
    flags: 'gi',
  },
  {
    id: 'url-sem-delimitador',
    grupo: 'Referências',
    severidade: 'padrao',
    titulo: 'URL sem sinais < >',
    descricao: 'Nas referências, o guia recomenda colocar endereços eletrônicos entre < e >.',
    regex: '(?<!<)https?:\\/\\/[^\\s<>]+(?!>)',
    flags: 'gi',
  },
  {
    id: 'disponivel-acesso',
    grupo: 'Referências',
    severidade: 'revisar',
    titulo: 'Referência online',
    descricao: 'Verificar se há Disponível em: e Acesso em: nas referências online.',
    regex: '\\b(?:Dispon[ií]vel em|Acesso em)\\b',
    flags: 'gi',
  },
  {
    id: 'seculo-maiusculo',
    grupo: 'Maiúsculas/minúsculas',
    severidade: 'padrao',
    titulo: 'Século em minúscula',
    descricao: 'O apêndice indica século com inicial minúscula, mesmo seguido de número.',
    regex: '\\bS[eé]culo\\s+[IVXLCDM]+\\b',
    flags: 'g',
  },
  {
    id: 'lei-sem-numero',
    grupo: 'Maiúsculas/minúsculas',
    severidade: 'revisar',
    titulo: 'Lei sem identificação',
    descricao: 'Lei com número/nome costuma usar maiúscula; lei genérica deve ser revisada.',
    regex: '\\bLei\\b(?!\\s+(?:n[ºo]|[0-9]|Complementar|Ordin[aá]ria|Org[aâ]nica))',
    flags: 'g',
  },
  {
    id: 'decreto-lei',
    grupo: 'Maiúsculas/minúsculas',
    severidade: 'revisar',
    titulo: 'Decreto-lei',
    descricao: 'Decreto-Lei com identificação; decreto-lei sem identificação.',
    regex: '\\b(?:decreto-lei|Decreto-lei|Decreto-Lei)\\b',
    flags: 'g',
  },
  {
    id: 'estrangeirismo',
    grupo: 'Itálico',
    severidade: 'revisar',
    titulo: 'Possível estrangeirismo',
    descricao: 'Palavras estrangeiras podem exigir itálico, salvo nomes de instituições, citações e textos técnicos.',
    regex: '\\b(?:online|habeas corpus|habitat|showm[ií]cio|ad referendum|superavit|deficit|Facebook|Twitter)\\b',
    flags: 'gi',
  },
  {
    id: 'aspas-retas',
    grupo: 'Aspas',
    severidade: 'padrao',
    titulo: 'Aspas retas',
    descricao: 'Verificar padronização de aspas tipográficas conforme o projeto editorial.',
    regex: '"[^"\\n]{2,}"',
    flags: 'g',
  },
  {
    id: 'reticencias-citacao',
    grupo: 'Citações',
    severidade: 'padrao',
    titulo: 'Reticências em citação',
    descricao: 'Supressões em citações devem usar reticências entre colchetes.',
    regex: '(?<!\\[)\\.\\.\\.(?!\\])',
    flags: 'g',
  },
  {
    id: 'enumeracao-ponto-virgula',
    grupo: 'Enumeração',
    severidade: 'revisar',
    titulo: 'Item de enumeração',
    descricao: 'Em enumerações após dois-pontos, conferir paralelismo de inicial e pontuação final.',
    regex: '(^|\\n)\\s*(?:[a-z]\\)|[0-9]+\\)|[IVXLCDM]+\\s*[–-])\\s+[^\\n]+',
    flags: 'g',
  },
  {
    id: 'enumeracao-minuscula-com-ponto',
    grupo: 'Enumeração',
    severidade: 'revisar',
    titulo: 'Item curto com minúscula e ponto final',
    descricao: 'Em enumerações curtas iniciadas por minúscula, o padrão costuma ser ponto e vírgula, deixando ponto final para o último item.',
    regex: '(^|\\n)\\s*(?:[a-z]\\)|[0-9]+\\)|[IVXLCDM]+\\s*[–-])\\s+[a-zà-ÿ][^\\n.;!?]{8,180}\\.(?=\\s*(?:\\n|$))',
    flags: 'g',
  },
  {
    id: 'enumeracao-maiuscula-com-ponto-virgula',
    grupo: 'Enumeração',
    severidade: 'revisar',
    titulo: 'Item com maiúscula e ponto e vírgula',
    descricao: 'Quando os itens começam com maiúscula, especialmente em enumerações longas, devem finalizar com ponto.',
    regex: '(^|\\n)\\s*(?:[a-z]\\)|[0-9]+\\)|[IVXLCDM]+\\s*[–-])\\s+[A-ZÀ-Ÿ][^\\n]+;',
    flags: 'g',
  },
  {
    id: 'enumeracao-longa-com-ponto-virgula',
    grupo: 'Enumeração',
    severidade: 'revisar',
    titulo: 'Item longo com ponto e vírgula',
    descricao: 'Itens longos ou com mais de uma frase geralmente pedem inicial maiúscula e ponto final.',
    regex: '(^|\\n)\\s*(?:[a-z]\\)|[0-9]+\\)|[IVXLCDM]+\\s*[–-])\\s+[^\\n]{180,};',
    flags: 'g',
  },
  {
    id: 'enumeracao-duas-frases-com-ponto-virgula',
    grupo: 'Enumeração',
    severidade: 'revisar',
    titulo: 'Item com mais de uma frase e ponto e vírgula',
    descricao: 'Quando o item tem mais de uma frase, tende a ser enumeração longa: conferir inicial maiúscula e ponto final.',
    regex: '(^|\\n)\\s*(?:[a-z]\\)|[0-9]+\\)|[IVXLCDM]+\\s*[–-])\\s+[^\\n]+\\.\\s+[A-ZÀ-Ÿ][^\\n]+;',
    flags: 'g',
  },
  {
    id: 'espaco-duplo',
    grupo: 'Limpeza',
    severidade: 'segura',
    titulo: 'Espaço duplo',
    descricao: 'Possível espaço duplicado no corpo do texto.',
    regex: '[^\\S\\r\\n]{2,}',
    flags: 'g',
  },
  {
    id: 'parenteses-colado',
    grupo: 'Limpeza',
    severidade: 'segura',
    titulo: 'Texto colado ao parêntese',
    descricao: 'Possível ausência de espaço após fechamento de parêntese.',
    regex: '\\)[A-Za-zÀ-ÿ]',
    flags: 'g',
  },
  {
    id: 'data-abreviada-texto-corrente',
    grupo: 'Datas e anos',
    severidade: 'revisar',
    titulo: 'Data abreviada',
    descricao: 'No texto corrente, datas devem ser escritas por extenso, como 7 de setembro de 1822. Usar forma abreviada apenas quando cabível.',
    regex: '\\b\\d{1,2}º?\\/\\d{1,2}\\/\\d{2,4}\\b',
    flags: 'g',
  },
  {
    id: 'data-zero-esquerda',
    grupo: 'Datas e anos',
    severidade: 'segura',
    titulo: 'Zero à esquerda em data',
    descricao: 'Em datas abreviadas, não se deve usar zero à esquerda: 8/10/1988, não 08/10/1988.',
    regex: '\\b(?:0\\d\\/\\d{1,2}\\/\\d{2,4}|\\d{1,2}\\/0\\d\\/\\d{2,4})\\b',
    flags: 'g',
  },
  {
    id: 'primeiro-dia-sem-ordinal',
    grupo: 'Datas e anos',
    severidade: 'segura',
    titulo: 'Primeiro dia sem ordinal',
    descricao: 'O primeiro dia do mês deve ser designado com ordinal: 1º de abril, não 1 de abril.',
    regex: '\\b1\\s+de\\s+(?:janeiro|fevereiro|março|marco|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro)\\b',
    flags: 'gi',
  },
  {
    id: 'decada-sem-seculo',
    grupo: 'Datas e anos',
    severidade: 'revisar',
    titulo: 'Década sem referência ao século',
    descricao: 'As décadas devem mencionar o século quando necessário: década de 1970 ou anos 1920, evitando formas como década de 70.',
    regex: '\\b(?:d[eé]cada de|anos)\\s+\\d{2}\\b',
    flags: 'gi',
  },
  {
    id: 'ano-dois-digitos',
    grupo: 'Datas e anos',
    severidade: 'revisar',
    titulo: 'Ano com dois dígitos',
    descricao: 'No texto corrente, o ano deve ter quatro dígitos.',
    regex: '\\b\\d{1,2}º?\\/\\d{1,2}\\/\\d{2}\\b',
    flags: 'g',
  },
  {
    id: 'horas-simbolo-com-ponto-ou-plural',
    grupo: 'Números - horas',
    severidade: 'segura',
    titulo: 'Símbolo de hora com ponto/plural',
    descricao: 'Os símbolos h, min e s devem vir sem ponto e sem plural.',
    regex: '\\b\\d{1,2}\\s*(?:hs\\.?|h\\.|mins?\\.?|min\\.|segs?\\.?|s\\.)\\b',
    flags: 'gi',
  },
  {
    id: 'horas-com-espaco',
    grupo: 'Números - horas',
    severidade: 'segura',
    titulo: 'Espaço antes do símbolo de hora',
    descricao: 'Não se usa espaço entre o número e o símbolo de hora, minuto ou segundo.',
    regex: '\\b\\d{1,2}\\s+(?:h|min|s)\\b',
    flags: 'gi',
  },
  {
    id: 'hora-minuto-com-min',
    grupo: 'Números - horas',
    severidade: 'segura',
    titulo: 'Minuto indicado com min em horário',
    descricao: 'Na menção de horas e minutos, usa-se 16h32, não 16h32min.',
    regex: '\\b\\d{1,2}h\\d{2}min\\b(?!\\d)',
    flags: 'gi',
  },
  {
    id: 'hora-minuto-segundo-com-s',
    grupo: 'Números - horas',
    severidade: 'segura',
    titulo: 'Segundo indicado com s em horário',
    descricao: 'Na menção de horas, minutos e segundos, usa-se 7h23min40, sem s.',
    regex: '\\b\\d{1,2}h\\d{2}min\\d{1,2}s\\b',
    flags: 'gi',
  },
  {
    id: 'horario-com-dois-pontos',
    grupo: 'Números - horas',
    severidade: 'revisar',
    titulo: 'Horário com dois-pontos',
    descricao: 'O padrão editorial usa forma como 16h32. Conferir casos escritos como 16:32.',
    regex: '\\b\\d{1,2}:\\d{2}(?::\\d{2})?\\b',
    flags: 'g',
  },
  {
    id: 'periodo-tempo-com-simbolo',
    grupo: 'Números - horas',
    severidade: 'revisar',
    titulo: 'Período de tempo com símbolo',
    descricao: 'Quando a referência for duração, preferir hora(s), minuto(s), segundo(s) por extenso, não símbolos.',
    regex: '\\b(?:por|durou|dura|duraram|durará|estendeu-se por|estenderam-se por|em)\\s+\\d+(?:h|min|s)\\b',
    flags: 'gi',
  },
  {
    id: 'inicio-periodo-com-numero',
    grupo: 'Números - início de período',
    severidade: 'revisar',
    titulo: 'Período iniciado por número',
    descricao: 'Não se deve iniciar período com números, exceto casos inevitáveis.',
    regex: '(^|[.!?]\\s+)[0-9]+(?:[.,][0-9]+)?%?\\s+[A-Za-zÀ-ÿ]',
    flags: 'g',
  },
  {
    id: 'numero-lei-por-extenso',
    grupo: 'Números - legislação',
    severidade: 'revisar',
    titulo: 'Número de lei por extenso',
    descricao: 'No texto corrido, os números das leis devem ser grafados em algarismos.',
    regex: '\\bLei\\s+(?:n[ºo]\\s+)?(?:um|uma|dois|duas|tr[eê]s|quatro|cinco|seis|sete|oito|nove|dez|onze|doze|treze|catorze|quatorze|quinze|dezesseis|dezessete|dezoito|dezenove|vinte)\\b',
    flags: 'gi',
  },
  {
    id: 'artigo-sem-abreviatura',
    grupo: 'Números - legislação',
    severidade: 'segura',
    titulo: 'Artigo sem abreviatura',
    descricao: 'Ao citar dispositivo normativo, usar art. ou arts., não artigo/artigos por extenso.',
    regex: '\\b[Aa]rtigos?\\s+\\d+\\b',
    flags: 'g',
  },
  {
    id: 'artigos-abreviatura-sem-ponto',
    grupo: 'Números - legislação',
    severidade: 'segura',
    titulo: 'Art./arts. sem ponto',
    descricao: 'As formas abreviadas corretas são art. e arts., com ponto.',
    regex: '\\barts?\\s+\\d+\\b',
    flags: 'gi',
  },
  {
    id: 'paragrafo-sem-simbolo',
    grupo: 'Números - legislação',
    severidade: 'segura',
    titulo: 'Parágrafo sem símbolo',
    descricao: 'Ao citar parágrafo de texto normativo, usar § ou §§.',
    regex: '\\b[Pp]ar[aá]grafos?\\s+(?:único|unico|\\d+)\\b',
    flags: 'g',
  },
  {
    id: 'paragrafo-ordinal-dez-ou-mais',
    grupo: 'Números - legislação',
    severidade: 'segura',
    titulo: 'Parágrafo acima de 9 com ordinal',
    descricao: 'Até o nove, usa-se ordinal. A partir do dez, usa-se apenas algarismo arábico: § 10.',
    regex: '§§?\\s*(?:1[0-9]|[2-9][0-9])º\\b',
    flags: 'g',
  },
  {
    id: 'paragrafo-ate-nove-sem-ordinal',
    grupo: 'Números - legislação',
    severidade: 'segura',
    titulo: 'Parágrafo até 9 sem ordinal',
    descricao: 'Na citação de parágrafos até nove, usar numeral ordinal: § 1º.',
    regex: '§§?\\s*[1-9](?!º|[0-9])\\b',
    flags: 'g',
  },
  {
    id: 'quantitativo-seguranca-especial',
    grupo: 'Números - legislação',
    severidade: 'revisar',
    titulo: 'Quantitativo em documento sensível',
    descricao: 'Em documentos administrativos que demandem segurança especial e em legislação, valores monetários, porcentagens e demais quantitativos devem ser escritos por extenso.',
    regex: '\\b(?:R\\$\\s*)?\\d+(?:[.,]\\d+)*(?:%|\\s*(?:reais|dólares|dolares|euros))?\\b',
    flags: 'gi',
  },
  {
    id: 'unidade-medida-com-ponto-ou-plural',
    grupo: 'Números - símbolos',
    severidade: 'segura',
    titulo: 'Unidade de medida com ponto/plural',
    descricao: 'Símbolos de unidades de medida devem vir sem ponto e sem plural.',
    regex: '\\b\\d+(?:[.,]\\d+)?\\s*(?:cms?\\.?|kgs?\\.?|mls?\\.?|lts?\\.?|ms?\\.?|kms?\\.?|g\\.|mg\\.)\\b',
    flags: 'gi',
  },
  {
    id: 'unidade-medida-com-espaco',
    grupo: 'Números - símbolos',
    severidade: 'segura',
    titulo: 'Espaço antes de unidade de medida',
    descricao: 'Símbolos de unidades de medida não são separados do número por espaço: 1cm, 1kg, 1ml.',
    regex: '\\b\\d+(?:[.,]\\d+)?\\s+(?:cm|kg|ml|l|L|m|km|g|mg)\\b',
    flags: 'g',
  },
  {
    id: 'intervalo-medida-sem-repetir-unidade',
    grupo: 'Números - símbolos',
    severidade: 'segura',
    titulo: 'Intervalo sem repetir unidade',
    descricao: 'Devem-se repetir as ordens de grandeza ao usar símbolos: de 3kg a 4kg.',
    regex: '\\b(?:de|entre)\\s+\\d+(?:[.,]\\d+)?\\s*(cm|kg|ml|l|L|m|km|g|mg)\\s+(?:a|e)\\s+\\d+(?:[.,]\\d+)?\\b(?!\\s*\\1)',
    flags: 'gi',
  },
  {
    id: 'milhar-sem-ponto',
    grupo: 'Números - pontuação',
    severidade: 'revisar',
    titulo: 'Milhar sem ponto',
    descricao: 'As centenas se separam por ponto, exceto em anos. Conferir números de quatro ou mais dígitos.',
    regex: '\\b(?!(?:1[5-9]|20)\\d{2}\\b)\\d{4,}\\b',
    flags: 'g',
  },
  {
    id: 'ano-com-ponto',
    grupo: 'Números - pontuação',
    severidade: 'segura',
    titulo: 'Ano com ponto de milhar',
    descricao: 'Anos não devem ter ponto de milhar: 2003, não 2.003.',
    regex: '\\b[12]\\.\\d{3}\\b',
    flags: 'g',
  },
  {
    id: 'virgula-dispositivo-ordem-logica',
    grupo: 'Pontuação - dispositivos',
    severidade: 'revisar',
    titulo: 'Vírgula em citação na ordem lógica',
    descricao: 'Quando o dispositivo vai do menor para o maior, em regra não se usa vírgula: inciso I do § 2º do art. 132.',
    regex: '\\b(?:inciso|item|al[ií]nea)\\s+[A-Za-z0-9IVXLCDM]+\\s*,\\s+(?:do|da|dos|das)\\s+(?:§|art\\.)\\b',
    flags: 'gi',
  },
  {
    id: 'virgula-artigo-ordem-logica',
    grupo: 'Pontuação - dispositivos',
    severidade: 'revisar',
    titulo: 'Vírgula entre artigo e norma',
    descricao: 'Na ordem lógica, evitar vírgula entre o artigo e a norma citada: O art. 37 da Lei 8.245, de 1991.',
    regex: '\\bart\\.\\s*\\d+[A-Za-zºª-]*\\s*,\\s+(?:da|do|das|dos)\\s+(?:Lei|Constitui[cç][aã]o|Decreto|Regimento|C[oó]digo)\\b',
    flags: 'gi',
  },
  {
    id: 'ordem-invertida-sem-virgula-artigo',
    grupo: 'Pontuação - dispositivos',
    severidade: 'revisar',
    titulo: 'Ordem invertida sem vírgula antes do artigo',
    descricao: 'Quando o maior elemento vem antes do menor, abrir o segmento intercalado com vírgula: Decreto 2.284, de 1937, art. 2º.',
    regex: '\\b(?:Lei|Decreto|Constitui[cç][aã]o|Regimento|C[oó]digo)\\s+(?:n[ºo]\\s*)?\\d[\\d.]*\\s+(?:de\\s+\\d{4}\\s+)?art\\.\\s*\\d+',
    flags: 'gi',
  },
  {
    id: 'ordem-invertida-sem-virgula-paragrafo',
    grupo: 'Pontuação - dispositivos',
    severidade: 'revisar',
    titulo: 'Ordem invertida sem vírgula em desdobramento',
    descricao: 'Em ordem maior-para-menor, cada segmento intercalado deve ser aberto e fechado por vírgulas: art. 171, § 1º, II, b, da CF.',
    regex: '\\bart\\.\\s*\\d+[A-Za-zºª-]*\\s+§\\s*\\d+º?(?:\\s+[IVXLCDM]+)?(?:\\s+[a-z])?\\b',
    flags: 'gi',
  },
  {
    id: 'sigla-com-pontos',
    grupo: 'Siglas',
    severidade: 'segura',
    titulo: 'Sigla com pontos',
    descricao: 'Não se usam pontos de separação entre as letras que formam a sigla.',
    regex: '\\b(?:[A-Z]\\.){2,}[A-Z]?\\b',
    flags: 'g',
  },
  {
    id: 'sigla-entre-aspas',
    grupo: 'Siglas',
    severidade: 'segura',
    titulo: 'Sigla entre aspas',
    descricao: 'Não se usam aspas em siglas.',
    regex: `[“"'']\\s*[A-ZÀ-Ÿ]{2,}\\s*[”"'']`,
    flags: 'g',
  },
  {
    id: 'sigla-plural-com-s',
    grupo: 'Siglas',
    severidade: 'segura',
    titulo: 'Sigla com s de plural',
    descricao: 'Com sigla empregada no plural, não se usa s minúsculo: os TRE, não os TREs.',
    regex: '\\b[A-ZÀ-Ÿ]{2,}s\\b',
    flags: 'g',
  },
  {
    id: 'sigla-partidaria-barra-sem-espaco',
    grupo: 'Siglas',
    severidade: 'segura',
    titulo: 'Sigla partidária/UF sem espaço na barra',
    descricao: 'Siglas partidárias seguidas de UF devem ter espaço antes e depois da barra: PT / SP.',
    regex: '\\b(?:MDB|PT|PSDB|PL|PP|PSD|PSB|PDT|PCdoB|PV|Republicanos|União|Uniao|Novo|Podemos|PSOL|Rede|Avante|Solidariedade|Cidadania|PRD|DC|PMB|PRTB|Agir|Mobiliza|UP|PCB|PCO|PSTU)\\s*/\\s*[A-Z]{2}\\b',
    flags: 'g',
  },
  {
    id: 'uf-sem-parenteses',
    grupo: 'Siglas',
    severidade: 'revisar',
    titulo: 'UF possivelmente sem parênteses',
    descricao: 'As siglas dos estados devem ser grafadas entre parênteses: João Pessoa (PB).',
    regex: '\\b[A-ZÀ-Ÿ][A-Za-zÀ-ÿ]+(?:\\s+[A-ZÀ-Ÿ][A-Za-zÀ-ÿ]+){0,3}\\s+(?:AC|AL|AP|AM|BA|CE|DF|ES|GO|MA|MT|MS|MG|PA|PB|PR|PE|PI|RJ|RN|RS|RO|RR|SC|SP|SE|TO)\\b',
    flags: 'g',
  },
  {
    id: 'sigla-sem-parenteses-apos-nome',
    grupo: 'Siglas',
    severidade: 'revisar',
    titulo: 'Sigla possivelmente fora de parênteses',
    descricao: 'Quando o nome estiver acompanhado da sigla, esta deve vir entre parênteses na primeira menção.',
    regex: '\\b[A-ZÀ-Ÿ][A-Za-zÀ-ÿ]+(?:\\s+(?:de|da|do|das|dos|e|para|com|em|no|na|nos|nas|[A-ZÀ-Ÿ][A-Za-zÀ-ÿ]+)){1,8}\\s+[A-ZÀ-Ÿ]{2,}\\b',
    flags: 'g',
  },
]
